=== matkowalski/magento2/dev/tests/functional/etc/global/variations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:annotation>
            <xs:documentation>
                The root element for configuration data.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="testCase" maxOccurs="unbounded" minOccurs="1">
                    <xs:annotation>
                        <xs:documentation>
                            An element that contains configuration data of a test case.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="testCase">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="variation" maxOccurs="unbounded" minOccurs="1">
                    <xs:annotation>
                        <xs:documentation>
                            An element that contains configuration data of a test case variation.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="variation">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="data" maxOccurs="unbounded" minOccurs="1">
                    <xs:annotation>
                        <xs:documentation>
                            An element that contains a single configuration data set of a test case variation.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="data">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute type="xs:string" name="name" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== matkowalski/magento2/dev/tests/functional/tests/app/Magento/Integration/Test/TestCase/UpdateIntegrationEntityTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/global/variations.xsd">
    <testCase name="UpdateIntegrationEntityTest">
        <variation name="UpdateIntegrationEntityTestVariation1">
            <data name="integration/data/name">Integration_%isolation%</data>
            <data name="integration/data/email">-</data>
            <data name="integration/data/endpoint">https://endpoint.com</data>
            <data name="integration/data/identity_link_url">https://testlink.com</data>
            <data name="integration/data/resource_access">-</data>
            <data name="integration/data/resources">-</data>
            <data name="constraint">assertIntegrationSuccessSaveMessage, assertIntegrationForm, assertIntegrationInGrid</data>
        </variation>
        <variation name="UpdateIntegrationEntityTestVariation2">
            <data name="integration/data/name">Integration_%isolation%</data>
            <data name="integration/data/email">-</data>
            <data name="integration/data/endpoint">-</data>
            <data name="integration/data/identity_link_url">-</data>
            <data name="integration/data/resource_access">Custom</data>
            <data name="integration/data/resources">Sales</data>
            <data name="constraint">assertIntegrationSuccessSaveMessage, assertIntegrationForm, assertIntegrationInGrid</data>
        </variation>
    </testCase>
</config>

=== matkowalski/magento2/dev/tests/functional/tests/app/Magento/Store/Test/TestCase/DeleteWebsiteEntityTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/global/variations.xsd">
    <testCase name="DeleteWebsiteEntityTest">
        <variation name="DeleteWebsiteEntityTestVariation1">
            <data name="website/dataSet">custom_website</data>
            <data name="createBackup">Yes</data>
            <data name="constraint">assertWebsiteSuccessDeleteAndBackupMessages, assertWebsiteNotInGrid, assertBackupInGrid</data>
        </variation>
        <variation name="DeleteWebsiteEntityTestVariation2">
            <data name="website/dataSet">custom_website</data>
            <data name="createBackup">No</data>
            <data name="constraint">assertWebsiteSuccessDeleteMessage, assertWebsiteNotInGrid</data>
        </variation>
    </testCase>
</config>

=== matkowalski/magento2/dev/tests/functional/tests/app/Magento/Review/Test/TestCase/CreateProductReviewBackendEntityTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/global/variations.xsd">
    <testCase name="CreateProductReviewBackendEntityTest">
        <variation name="CreateProductReviewBackendEntityTestVariation1">
            <data name="review/data/type">Administrator</data>
            <data name="review/data/entity_id/dataSet">catalogProductSimple::default</data>
            <data name="review/data/status_id">Approved</data>
            <data name="review/data/select_stores/0">Main Website/Main Website Store/Default Store View</data>
            <data name="review/data/ratings/rating_0/dataSet">visibleOnDefaultWebsite</data>
            <data name="review/data/ratings/rating_0/rating">3</data>
            <data name="review/data/nickname">John</data>
            <data name="review/data/title">title %isolation%</data>
            <data name="review/data/detail">review detail %isolation%</data>
            <data name="constraint">assertProductReviewBackendSuccessSaveMessage, assertProductReviewInGrid, assertProductRatingInProductPage</data>
        </variation>
        <variation name="CreateProductReviewBackendEntityTestVariation2">
            <data name="review/data/type">Administrator</data>
            <data name="review/data/entity_id/dataSet">catalogProductSimple::default</data>
            <data name="review/data/status_id">Pending</data>
            <data name="review/data/select_stores/0">Main Website/Main Website Store/Default Store View</data>
            <data name="review/data/ratings/rating_0/dataSet">visibleOnDefaultWebsite</data>
            <data name="review/data/ratings/rating_0/rating">4</data>
            <data name="review/data/nickname">Britney</data>
            <data name="review/data/title">title %isolation%</data>
            <data name="review/data/detail">review detail %isolation%</data>
            <data name="constraint">assertProductReviewBackendSuccessSaveMessage, assertProductReviewInGrid, assertProductRatingInProductPage</data>
        </variation>
        <variation name="CreateProductReviewBackendEntityTestVariation3">
            <data name="review/data/type">Administrator</data>
            <data name="review/data/entity_id/dataSet">catalogProductSimple::default</data>
            <data name="review/data/status_id">Not Approved</data>
            <data name="review/data/select_stores/0">Main Website/Main Website Store/Default Store View</data>
            <data name="review/data/ratings/rating_0/dataSet">visibleOnDefaultWebsite</data>
            <data name="review/data/ratings/rating_0/rating">5</data>
            <data name="review/data/nickname">Michael</data>
            <data name="review/data/title">title %isolation%</data>
            <data name="review/data/detail">review detail %isolation%</data>
            <data name="constraint">assertProductReviewBackendSuccessSaveMessage, assertProductReviewInGrid, assertProductRatingInProductPage</data>
        </variation>
    </testCase>
</config>

=== matkowalski/magento2/dev/tests/functional/tests/app/Magento/User/Test/TestCase/UpdateAdminUserEntityTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/global/variations.xsd">
    <testCase name="UpdateAdminUserEntityTest">
        <variation name="UpdateAdminUserEntityTestVariation1">
            <data name="initialUser/dataSet">custom_admin_with_default_role</data>
            <data name="user/data/username">NewAdminUser%isolation%</data>
            <data name="user/data/firstname">NewFirstName%isolation%</data>
            <data name="user/data/lastname">NewLastName%isolation%</data>
            <data name="user/data/email">NewEmail%isolation%@example.com</data>
            <data name="user/data/password">123123qa</data>
            <data name="user/data/password_confirmation">123123qa</data>
            <data name="user/data/is_active">-</data>
            <data name="user/data/role_id/dataSet">-</data>
            <data name="loginAsDefaultAdmin">0</data>
            <data name="constraint">assertUserSuccessSaveMessage, assertUserInGrid, assertUserSuccessLogOut, assertUserSuccessLogin</data>
            <data name="user/data/current_password">123123q</data>
        </variation>
        <variation name="UpdateAdminUserEntityTestVariation2">
            <data name="initialUser/dataSet">custom_admin_with_default_role</data>
            <data name="user/data/username">-</data>
            <data name="user/data/firstname">-</data>
            <data name="user/data/lastname">-</data>
            <data name="user/data/email">-</data>
            <data name="user/data/password">-</data>
            <data name="user/data/password_confirmation">-</data>
            <data name="user/data/is_active">-</data>
            <data name="user/data/role_id/dataSet">role_sales</data>
            <data name="loginAsDefaultAdmin">0</data>
            <data name="constraint">assertUserSuccessSaveMessage, assertUserInGrid, assertUserSuccessLogOut, assertUserSuccessLogin, assertUserRoleSalesRestrictedAccess</data>
            <data name="user/data/current_password">123123q</data>
        </variation>
        <variation name="UpdateAdminUserEntityTestVariation3">
            <data name="initialUser/dataSet">custom_admin_with_default_role</data>
            <data name="user/data/username">-</data>
            <data name="user/data/firstname">-</data>
            <data name="user/data/lastname">-</data>
            <data name="user/data/email">-</data>
            <data name="user/data/password">-</data>
            <data name="user/data/password_confirmation">-</data>
            <data name="user/data/is_active">Inactive</data>
            <data name="user/data/role_id/dataSet">-</data>
            <data name="loginAsDefaultAdmin">1</data>
            <data name="constraint">assertUserSuccessSaveMessage, assertUserInGrid, assertUserSuccessLogOut, assertUserWrongCredentialsMessage</data>
            <data name="user/data/current_password">123123q</data>
        </variation>
    </testCase>
</config>

=== matkowalski/magento2/dev/tests/functional/tests/app/Magento/CatalogRule/Test/TestCase/UpdateCatalogPriceRuleEntityTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/global/variations.xsd">
    <testCase name="UpdateCatalogPriceRuleEntityTest">
        <variation name="UpdateCatalogPriceRuleEntityTestVariation1">
            <data name="catalogPriceRuleOriginal/dataSet">active_catalog_price_rule_with_conditions</data>
            <data name="catalogPriceRule/data/name">New Catalog Price Rule Name %isolation%</data>
            <data name="catalogPriceRule/data/description">-</data>
            <data name="catalogPriceRule/data/is_active">Inactive</data>
            <data name="catalogPriceRule/data/conditions">-</data>
            <data name="catalogPriceRule/data/simple_action">-</data>
            <data name="catalogPriceRule/data/discount_amount">-</data>
            <data name="saveAction">save</data>
            <data name="price/sub_total">-</data>
            <data name="price/grand_total">-</data>
            <data name="price/discount_amount">-</data>
            <data name="price/special">-</data>
            <data name="price/regular">-</data>
            <data name="constraint">assertCatalogPriceRuleSuccessSaveMessage, assertCatalogPriceRuleNoticeMessage, assertCatalogPriceRuleForm, assertCatalogPriceRuleInGrid</data>
        </variation>
        <variation name="UpdateCatalogPriceRuleEntityTestVariation2">
            <data name="catalogPriceRuleOriginal/dataSet">active_catalog_price_rule_with_conditions</data>
            <data name="catalogPriceRule/data/name">New Catalog Price Rule Name %isolation%</data>
            <data name="catalogPriceRule/data/description">New Catalog Price Rule Description %isolation%</data>
            <data name="catalogPriceRule/data/is_active">Active</data>
            <data name="catalogPriceRule/data/conditions">[Category|is|%category_1%]</data>
            <data name="catalogPriceRule/data/simple_action">By Fixed Amount</data>
            <data name="catalogPriceRule/data/discount_amount">35</data>
            <data name="saveAction">saveAndApply</data>
            <data name="price/sub_total">100</data>
            <data name="price/grand_total">65</data>
            <data name="price/discount_amount">35</data>
            <data name="price/special">65</data>
            <data name="price/regular">100</data>
            <data name="constraint">assertCatalogPriceRuleSuccessSaveMessage, assertCatalogPriceRuleAppliedProductPage, assertCatalogPriceRuleForm, assertCatalogPriceRuleInGrid</data>
        </variation>
    </testCase>
</config>

=== matkowalski/magento2/dev/tests/functional/tests/app/Magento/User/Test/TestCase/CreateAdminUserEntityTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/global/variations.xsd">
    <testCase name="CreateAdminUserEntityTest">
        <variation name="CreateAdminUserEntityTestVariation1">
            <data name="user/data/username">AdminUser%isolation%</data>
            <data name="user/data/firstname">FirstName%isolation%</data>
            <data name="user/data/lastname">LastName%isolation%</data>
            <data name="user/data/email">email%isolation%@example.com</data>
            <data name="user/data/password">123123q</data>
            <data name="user/data/password_confirmation">123123q</data>
            <data name="user/data/is_active">Active</data>
            <data name="user/data/role_id/dataSet">Administrators</data>
            <data name="isDuplicated">-</data>
            <data name="constraint">assertUserSuccessSaveMessage, assertUserInGrid, assertUserSuccessLogOut, assertUserSuccessLogin</data>
            <data name="user/data/current_password">%current_password%</data>
        </variation>
        <variation name="CreateAdminUserEntityTestVariation2">
            <data name="user/data/username">AdminUser%isolation%</data>
            <data name="user/data/firstname">FirstName%isolation%</data>
            <data name="user/data/lastname">LastName%isolation%</data>
            <data name="user/data/email">email%isolation%@example.com</data>
            <data name="user/data/password">123123q</data>
            <data name="user/data/password_confirmation">123123q</data>
            <data name="user/data/is_active">Inactive</data>
            <data name="user/data/role_id/dataSet">Administrators</data>
            <data name="isDuplicated">-</data>
            <data name="constraint">assertUserSuccessSaveMessage, assertUserInGrid, assertUserSuccessLogOut, assertUserWrongCredentialsMessage</data>
            <data name="user/data/current_password">%current_password%</data>
        </variation>
        <variation name="CreateAdminUserEntityTestVariation3">
            <data name="user/data/username">-</data>
            <data name="user/data/firstname">FirstName%isolation%</data>
            <data name="user/data/lastname">LastName%isolation%</data>
            <data name="user/data/email">email%isolation%@example.com</data>
            <data name="user/data/password">123123q</data>
            <data name="user/data/password_confirmation">123123q</data>
            <data name="user/data/is_active">Active</data>
            <data name="user/data/role_id/dataSet">Administrators</data>
            <data name="isDuplicated">username</data>
            <data name="constraint">assertUserDuplicateMessage</data>
            <data name="user/data/current_password">%current_password%</data>
        </variation>
        <variation name="CreateAdminUserEntityTestVariation4">
            <data name="user/data/username">AdminUser%isolation%</data>
            <data name="user/data/firstname">FirstName%isolation%</data>
            <data name="user/data/lastname">LastName%isolation%</data>
            <data name="user/data/email">-</data>
            <data name="user/data/password">123123q</data>
            <data name="user/data/password_confirmation">123123q</data>
            <data name="user/data/is_active">Active</data>
            <data name="user/data/role_id/dataSet">Administrators</data>
            <data name="isDuplicated">email</data>
            <data name="constraint">assertUserDuplicateMessage</data>
            <data name="user/data/current_password">%current_password%</data>
        </variation>
        <variation name="CreateAdminUserEntityTestVariation5">
            <data name="user/data/username">AdminUser%isolation%</data>
            <data name="user/data/firstname">FirstName%isolation%</data>
            <data name="user/data/lastname">LastName%isolation%</data>
            <data name="user/data/email">email%isolation%@example.com</data>
            <data name="user/data/password">123123q</data>
            <data name="user/data/password_confirmation">123123q</data>
            <data name="user/data/is_active">Active</data>
            <data name="user/data/role_id/dataSet">-</data>
            <data name="isDuplicated">-</data>
            <data name="constraint">assertUserSuccessSaveMessage, assertUserInGrid, assertUserSuccessLogOut, assertUserWrongCredentialsMessage</data>
            <data name="user/data/current_password">%current_password%</data>
        </variation>
        <variation name="CreateAdminUserEntityTestVariation6">
            <data name="user/data/username">AdminUser%isolation%</data>
            <data name="user/data/firstname">FirstName%isolation%</data>
            <data name="user/data/lastname">LastName%isolation%</data>
            <data name="user/data/email">email%isolation%@example.cim</data>
            <data name="user/data/password">123123q</data>
            <data name="user/data/password_confirmation">123123q</data>
            <data name="user/data/is_active">Active</data>
            <data name="user/data/role_id/dataSet">-</data>
            <data name="isDuplicated">-</data>
            <data name="constraint">assertUserInvalidEmailMessage</data>
            <data name="user/data/current_password">%current_password%</data>
        </variation>
    </testCase>
</config>

=== matkowalski/magento2/dev/tests/functional/tests/app/Magento/Review/Test/TestCase/ManageProductReviewFromCustomerPageTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/global/variations.xsd">
    <testCase name="ManageProductReviewFromCustomerPageTest">
        <variation name="ManageProductReviewFromCustomerPageTestVariation1">
            <data name="review/data/status_id">Approved</data>
            <data name="review/data/nickname">name_upd_%isolation%</data>
            <data name="review/data/title">title_upd_%isolation%</data>
            <data name="review/data/detail">review_upd_%isolation%</data>
            <data name="constraint">assertReviewSuccessSaveMessage, assertProductReviewInGridOnCustomerPage, assertProductReviewOnProductPage</data>
        </variation>
        <variation name="ManageProductReviewFromCustomerPageTestVariation2">
            <data name="review/data/status_id">Not Approved</data>
            <data name="review/data/nickname">name_upd_%isolation%</data>
            <data name="review/data/title">title_upd_%isolation%</data>
            <data name="review/data/detail">review_upd_%isolation%</data>
            <data name="constraint">assertReviewSuccessSaveMessage, assertProductReviewInGridOnCustomerPage, assertProductRatingNotInProductPage</data>
        </variation>
    </testCase>
</config>

=== matkowalski/magento2/dev/tests/functional/tests/app/Magento/Catalog/Test/TestCase/ProductAttribute/DeleteProductAttributeEntityTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../etc/global/variations.xsd">
    <testCase name="DeleteProductAttributeEntityTest">
        <variation name="DeleteProductAttributeEntityTestVariation1">
            <data name="attribute/dataSet">attribute_type_text_field</data>
            <data name="isRequired">Yes</data>
            <data name="constraint">assertProductAttributeSuccessDeleteMessage, assertProductAttributeAbsenceInGrid, assertProductAttributeAbsenceInSearchOnProductForm, assertProductAttributeAbsenceForExport</data>
        </variation>
        <variation name="DeleteProductAttributeEntityTestVariation2">
            <data name="attribute/dataSet">attribute_type_dropdown</data>
            <data name="isRequired">No</data>
            <data name="constraint">assertProductAttributeSuccessDeleteMessage, assertProductAttributeAbsenceInGrid, assertProductAttributeAbsenceInSearchOnProductForm, assertProductAttributeAbsenceForExport</data>
        </variation>
    </testCase>
</config>
