=== matkowalski/magento2/dev/tests/functional/etc/global/variations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:annotation>
            <xs:documentation>
                The root element for configuration data.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="testCase" maxOccurs="unbounded" minOccurs="1">
                    <xs:annotation>
                        <xs:documentation>
                            An element that contains configuration data of a test case.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="testCase">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="variation" maxOccurs="unbounded" minOccurs="1">
                    <xs:annotation>
                        <xs:documentation>
                            An element that contains configuration data of a test case variation.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="variation">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="data" maxOccurs="unbounded" minOccurs="1">
                    <xs:annotation>
                        <xs:documentation>
                            An element that contains a single configuration data set of a test case variation.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="data">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute type="xs:string" name="name" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== matkowalski/magento2/dev/tests/functional/tests/app/Magento/Review/Test/TestCase/CreateProductReviewFrontendEntityTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/global/variations.xsd">
    <testCase name="CreateProductReviewFrontendEntityTest">
        <variation name="CreateProductReviewFrontendEntityTestVariation1">
            <data name="description">Create product review with rating</data>
            <data name="review/data/customer">-</data>
            <data name="review/data/nickname">name_%isolation%</data>
            <data name="review/data/title">title_%isolation%</data>
            <data name="review/data/detail">review_%isolation%</data>
            <data name="review/data/ratings/1/dataSet">visibleOnDefaultWebsite</data>
            <data name="review/data/ratings/1/rating">4</data>
            <data name="review/data/entity_id/dataSet">catalogProductSimple::default</data>
            <data name="constraint">assertReviewCreationSuccessMessage, assertProductReviewInGrid, assertProductRatingOnReviewPage, assertProductRatingInProductPage</data>
        </variation>
        <variation name="CreateProductReviewFrontendEntityTestVariation2">
            <data name="description">MAGETWO-12403 - Add Product Review from Customer's Prospective</data>
            <data name="review/data/customer">Guest</data>
            <data name="review/data/nickname">name_%isolation%</data>
            <data name="review/data/title">title_%isolation%</data>
            <data name="review/data/detail">review_%isolation%</data>
            <data name="review/data/ratings/1/dataSet">-</data>
            <data name="review/data/ratings/1/rating">-</data>
            <data name="review/data/entity_id/dataSet">catalogProductSimple::default</data>
            <data name="constraint">assertReviewCreationSuccessMessage, assertProductReviewIsAbsentOnProductPage, assertProductReviewForm, assertSetApprovedProductReview, assertReviewLinksIsPresentOnProductPage, assertProductReviewOnProductPage</data>
            <data name="tag">bamboo_plan:end_to_end,test_type:acceptance_test</data>
        </variation>
    </testCase>
</config>

=== matkowalski/magento2/dev/tests/functional/tests/app/Magento/Store/Test/TestCase/CreateStoreGroupEntityTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/global/variations.xsd">
    <testCase name="CreateStoreGroupEntityTest">
        <variation name="CreateStoreGroupEntityTestVariation1">
            <data name="storeGroup/data/website_id/dataSet">main_website</data>
            <data name="storeGroup/data/name">store_name_%isolation%</data>
            <data name="storeGroup/data/root_category_id/dataSet">default_category</data>
            <data name="constraint">assertStoreGroupSuccessSaveMessage, assertStoreGroupInGrid, assertStoreGroupForm, assertStoreGroupOnStoreViewForm</data>
        </variation>
        <variation name="CreateStoreGroupEntityTestVariation2">
            <data name="storeGroup/data/website_id/dataSet">custom_website</data>
            <data name="storeGroup/data/name">store_name_%isolation%</data>
            <data name="storeGroup/data/root_category_id/dataSet">root_category</data>
            <data name="constraint">assertStoreGroupSuccessSaveMessage, assertStoreGroupInGrid, assertStoreGroupForm, assertStoreGroupOnStoreViewForm</data>
        </variation>
    </testCase>
</config>

=== matkowalski/magento2/dev/tests/functional/tests/app/Magento/Tax/Test/TestCase/UpdateTaxRateEntityTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/global/variations.xsd">
    <testCase name="UpdateTaxRateEntityTest">
        <variation name="UpdateTaxRateEntityTestVariation1">
            <data name="initialTaxRate/dataSet">default</data>
            <data name="taxRate/data/code">TaxIdentifier%isolation%</data>
            <data name="taxRate/data/zip_is_range">No</data>
            <data name="taxRate/data/zip_from">-</data>
            <data name="taxRate/data/zip_to">-</data>
            <data name="taxRate/data/tax_postcode">90001</data>
            <data name="taxRate/data/tax_country_id">United States</data>
            <data name="taxRate/data/tax_region_id">California</data>
            <data name="taxRate/data/rate">100</data>
            <data name="constraint">assertTaxRateSuccessSaveMessage, assertTaxRateInGrid, assertTaxRateForm</data>
        </variation>
        <variation name="UpdateTaxRateEntityTestVariation2">
            <data name="initialTaxRate/dataSet">default</data>
            <data name="taxRate/data/code">TaxIdentifier%isolation%</data>
            <data name="taxRate/data/zip_is_range">Yes</data>
            <data name="taxRate/data/zip_from">90001</data>
            <data name="taxRate/data/zip_to">96162</data>
            <data name="taxRate/data/tax_postcode">-</data>
            <data name="taxRate/data/tax_country_id">United States</data>
            <data name="taxRate/data/tax_region_id">California</data>
            <data name="taxRate/data/rate">15.05</data>
            <data name="constraint">assertTaxRateSuccessSaveMessage, assertTaxRateInGrid, assertTaxRateForm</data>
        </variation>
        <variation name="UpdateTaxRateEntityTestVariation3">
            <data name="initialTaxRate/dataSet">default</data>
            <data name="taxRate/data/code">TaxIdentifier%isolation%</data>
            <data name="taxRate/data/zip_is_range">No</data>
            <data name="taxRate/data/zip_from">-</data>
            <data name="taxRate/data/zip_to">-</data>
            <data name="taxRate/data/tax_postcode">*</data>
            <data name="taxRate/data/tax_country_id">United Kingdom</data>
            <data name="taxRate/data/tax_region_id">*</data>
            <data name="taxRate/data/rate">777</data>
            <data name="constraint">assertTaxRateIsInCorrectRange</data>
        </variation>
        <variation name="UpdateTaxRateEntityTestVariation4">
            <data name="initialTaxRate/dataSet">withZipRange</data>
            <data name="taxRate/data/code">TaxIdentifier%isolation%</data>
            <data name="taxRate/data/zip_is_range">No</data>
            <data name="taxRate/data/zip_from">-</data>
            <data name="taxRate/data/zip_to">-</data>
            <data name="taxRate/data/tax_postcode">180</data>
            <data name="taxRate/data/tax_country_id">Canada</data>
            <data name="taxRate/data/tax_region_id">*</data>
            <data name="taxRate/data/rate">25</data>
            <data name="constraint">assertTaxRateSuccessSaveMessage, assertTaxRateInGrid, assertTaxRateForm</data>
        </variation>
        <variation name="UpdateTaxRateEntityTestVariation5">
            <data name="initialTaxRate/dataSet">withZipRange</data>
            <data name="taxRate/data/code">TaxIdentifier%isolation%</data>
            <data name="taxRate/data/zip_is_range">Yes</data>
            <data name="taxRate/data/zip_to">7800935</data>
            <data name="taxRate/data/tax_postcode">-</data>
            <data name="taxRate/data/tax_country_id">United Kingdom</data>
            <data name="taxRate/data/tax_region_id">*</data>
            <data name="constraint">assertTaxRateIsInCorrectRange</data>
        </variation>
        <variation name="UpdateTaxRateEntityTestVariation6">
            <data name="initialTaxRate/dataSet">withZipRange</data>
            <data name="taxRate/data/code">TaxIdentifier%isolation%</data>
            <data name="taxRate/data/zip_is_range">No</data>
            <data name="taxRate/data/zip_from">-</data>
            <data name="taxRate/data/zip_to">-</data>
            <data name="taxRate/data/tax_postcode">*</data>
            <data name="taxRate/data/tax_country_id">France</data>
            <data name="taxRate/data/tax_region_id">Val-d'Oise</data>
            <data name="taxRate/data/rate">0.1</data>
            <data name="constraint">assertTaxRateSuccessSaveMessage, assertTaxRateInGrid, assertTaxRateForm</data>
        </variation>
    </testCase>
</config>

=== matkowalski/magento2/dev/tests/functional/tests/app/Magento/Catalog/Test/TestCase/ProductAttribute/UpdateAttributeSetTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../etc/global/variations.xsd">
    <testCase name="UpdateAttributeSetTest">
        <variation name="UpdateAttributeSetTestVariation1">
            <data name="attributeSet/data/attribute_set_name">ProductTemplateEdit1%isolation%</data>
            <data name="attributeSet/data/group">Custom-group%isolation%</data>
            <data name="attributeSetOriginal/dataSet">custom_attribute_set</data>
            <data name="productAttributeOriginal/dataSet">attribute_type_text_field</data>
            <data name="constraint">assertProductTemplateSuccessSaveMessage, assertProductTemplateForm, assertProductTemplateInGrid, assertProductTemplateOnProductForm, assertProductTemplateGroupOnProductForm</data>
        </variation>
    </testCase>
</config>

=== matkowalski/magento2/dev/tests/functional/tests/app/Magento/Customer/Test/TestCase/CreateCustomerFrontendEntityTest/testCreateCustomer.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../etc/global/variations.xsd">
    <testCase name="testCreateCustomer">
        <variation name="testCreateCustomerVariation1">
            <data name="customer/data/firstname">john</data>
            <data name="customer/data/lastname">doe</data>
            <data name="customer/data/email">johndoe%isolation%@example.com</data>
            <data name="customer/data/is_subscribed">No</data>
            <data name="customer/data/password">123123q</data>
            <data name="customer/data/password_confirmation">123123q</data>
            <data name="constraint">assertCustomerSuccessRegisterMessage, assertCustomerInGrid</data>
        </variation>
        <variation name="testCreateCustomerVariation2">
            <data name="customer/data/firstname">john</data>
            <data name="customer/data/lastname">doe</data>
            <data name="customer/data/email">johndoe%isolation%@example.com</data>
            <data name="customer/data/is_subscribed">Yes</data>
            <data name="customer/data/password">123123q</data>
            <data name="customer/data/password_confirmation">123123q</data>
            <data name="constraint">assertCustomerSuccessRegisterMessage, assertCustomerInGrid, assertCustomerForm, assertCustomerIsSubscribedToNewsletter</data>
        </variation>
    </testCase>
</config>

=== matkowalski/magento2/dev/tests/functional/tests/app/Magento/User/Test/TestCase/DeleteUserRoleEntityTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/global/variations.xsd">
    <testCase name="DeleteUserRoleEntityTest">
        <variation name="DeleteUserRoleEntityTestVariation1">
            <data name="isDefaultUser">0</data>
            <data name="constraint">assertImpossibleDeleteYourOwnRole, assertRoleInGrid</data>
        </variation>
        <variation name="DeleteUserRoleEntityTestVariation2">
            <data name="isDefaultUser">1</data>
            <data name="constraint">assertRoleSuccessDeleteMessage, assertRoleNotInGrid</data>
        </variation>
    </testCase>
</config>

=== matkowalski/magento2/dev/tests/functional/tests/app/Magento/Review/Test/TestCase/MassActionsProductReviewEntityTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/global/variations.xsd">
    <testCase name="MassActionsProductReviewEntityTest">
        <variation name="MassActionsProductReviewEntityTestVariation1">
            <data name="gridActions">Update Status</data>
            <data name="gridStatus">Approved</data>
            <data name="constraint">assertProductReviewMassActionSuccessMessage, assertProductReviewInGrid, assertProductRatingInProductPage</data>
        </variation>
        <variation name="MassActionsProductReviewEntityTestVariation2">
            <data name="gridActions">Update Status</data>
            <data name="gridStatus">Pending</data>
            <data name="constraint">assertProductReviewMassActionSuccessMessage, assertProductReviewInGrid, assertProductRatingNotInProductPage</data>
        </variation>
        <variation name="MassActionsProductReviewEntityTestVariation3">
            <data name="gridActions">Update Status</data>
            <data name="gridStatus">Not Approved</data>
            <data name="constraint">assertProductReviewMassActionSuccessMessage, assertProductReviewInGrid, assertProductRatingNotInProductPage</data>
        </variation>
        <variation name="MassActionsProductReviewEntityTestVariation4">
            <data name="gridActions">Delete</data>
            <data name="gridStatus">-</data>
            <data name="constraint">assertProductReviewMassActionSuccessDeleteMessage, assertProductRatingNotInProductPage</data>
        </variation>
    </testCase>
</config>

=== matkowalski/magento2/dev/tests/functional/tests/app/Magento/Checkout/Test/TestCase/AddProductsToShoppingCartEntityTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/global/variations.xsd">
    <testCase name="AddProductsToShoppingCartEntityTest">
        <variation name="AddProductsToShoppingCartEntityTestVariation1">
            <data name="productsData">bundleProduct::bundle_dynamic_product</data>
            <data name="cart/data/grand_total">200</data>
            <data name="constraint">assertPriceInShoppingCart, assertProductQtyInShoppingCart, assertSubtotalInShoppingCart, assertCartItemsOptions, assertGrandTotalInShoppingCart</data>
        </variation>
        <variation name="AddProductsToShoppingCartEntityTestVariation2">
            <data name="productsData">bundleProduct::bundle_fixed_product</data>
            <data name="cart/data/grand_total">756</data>
            <data name="constraint">assertPriceInShoppingCart, assertProductQtyInShoppingCart, assertSubtotalInShoppingCart, assertCartItemsOptions, assertGrandTotalInShoppingCart</data>
        </variation>
        <variation name="AddProductsToShoppingCartEntityTestVariation3">
            <data name="productsData">catalogProductSimple::with_two_custom_option</data>
            <data name="cart/data/grand_total">340</data>
            <data name="constraint">assertPriceInShoppingCart, assertProductQtyInShoppingCart, assertSubtotalInShoppingCart, assertCartItemsOptions, assertGrandTotalInShoppingCart</data>
        </variation>
        <variation name="AddProductsToShoppingCartEntityTestVariation4">
            <data name="productsData">catalogProductVirtual::product_50_dollar</data>
            <data name="cart/data/grand_total">50</data>
            <data name="constraint">assertPriceInShoppingCart, assertProductQtyInShoppingCart, assertSubtotalInShoppingCart, assertCartItemsOptions, assertGrandTotalInShoppingCart</data>
        </variation>
        <variation name="AddProductsToShoppingCartEntityTestVariation5">
            <data name="productsData">configurableProductInjectable::default</data>
            <data name="cart/data/grand_total">516</data>
            <data name="constraint">assertPriceInShoppingCart, assertProductQtyInShoppingCart, assertSubtotalInShoppingCart, assertCartItemsOptions, assertGrandTotalInShoppingCart</data>
        </variation>
        <variation name="AddProductsToShoppingCartEntityTestVariation6">
            <data name="productsData">downloadableProductInjectable::with_two_separately_links</data>
            <data name="cart/data/grand_total">46</data>
            <data name="constraint">assertPriceInShoppingCart, assertProductQtyInShoppingCart, assertSubtotalInShoppingCart, assertCartItemsOptions, assertGrandTotalInShoppingCart</data>
        </variation>
        <variation name="AddProductsToShoppingCartEntityTestVariation7">
            <data name="productsData">groupedProductInjectable::three_simple_products</data>
            <data name="cart/data/grand_total">1920</data>
            <data name="constraint">assertPriceInShoppingCart, assertProductQtyInShoppingCart, assertSubtotalInShoppingCart, assertCartItemsOptions, assertGrandTotalInShoppingCart</data>
        </variation>
        <variation name="AddProductsToShoppingCartEntityTestVariation8">
            <data name="productsData">catalogProductSimple::with_two_custom_option, catalogProductVirtual::product_50_dollar, downloadableProductInjectable::with_two_separately_links, groupedProductInjectable::three_simple_products, configurableProductInjectable::default, bundleProduct::bundle_dynamic_product, bundleProduct::bundle_dynamic_product</data>
            <data name="cart/data/grand_total">3272</data>
            <data name="constraint">assertPriceInShoppingCart, assertProductQtyInShoppingCart, assertSubtotalInShoppingCart, assertCartItemsOptions, assertGrandTotalInShoppingCart</data>
        </variation>
    </testCase>
</config>
