=== matkowalski/magento2/dev/tests/functional/etc/global/variations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:annotation>
            <xs:documentation>
                The root element for configuration data.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="testCase" maxOccurs="unbounded" minOccurs="1">
                    <xs:annotation>
                        <xs:documentation>
                            An element that contains configuration data of a test case.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="testCase">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="variation" maxOccurs="unbounded" minOccurs="1">
                    <xs:annotation>
                        <xs:documentation>
                            An element that contains configuration data of a test case variation.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="variation">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="data" maxOccurs="unbounded" minOccurs="1">
                    <xs:annotation>
                        <xs:documentation>
                            An element that contains a single configuration data set of a test case variation.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="data">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute type="xs:string" name="name" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== matkowalski/magento2/dev/tests/functional/tests/app/Magento/Sitemap/Test/TestCase/CreateSitemapEntityTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/global/variations.xsd">
    <testCase name="CreateSitemapEntityTest">
        <variation name="CreateSitemapEntityTestVariation1">
            <data name="sitemap/data/sitemap_filename">sitemap.xml</data>
            <data name="sitemap/data/sitemap_path">/</data>
            <data name="constraint">assertSitemapSuccessSaveMessage, assertSitemapInGrid</data>
        </variation>
        <variation name="CreateSitemapEntityTestVariation2">
            <data name="sitemap/data/sitemap_filename">%isolation%</data>
            <data name="sitemap/data/sitemap_path">/</data>
            <data name="constraint">assertSitemapFailPathSaveMessage</data>
        </variation>
        <variation name="CreateSitemapEntityTestVariation3">
            <data name="sitemap/data/sitemap_filename">sitemap.xml</data>
            <data name="sitemap/data/sitemap_path">/%isolation%</data>
            <data name="constraint">assertSitemapFailFolderSaveMessage</data>
        </variation>
    </testCase>
</config>

=== matkowalski/magento2/dev/tests/functional/tests/app/Magento/User/Test/TestCase/UserLoginAfterChangingPermissionsTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/global/variations.xsd">
    <testCase name="UserLoginAfterChangingPermissionsTest">
        <variation name="UserLoginAfterChangingPermissionsTestVariation1">
            <data name="role/data/rolename">AdminRole%isolation%</data>
            <data name="role/data/resource_access">Custom</data>
            <data name="role/data/roles_resources">Sales</data>
            <data name="updatedRole/data/rolename">UpdatedAdminRole%isolation%</data>
            <data name="updatedRole/data/resource_access">All</data>
            <data name="constraint">assertUserSuccessLogin</data>
        </variation>
    </testCase>
</config>

=== matkowalski/magento2/dev/tests/functional/tests/app/Magento/Integration/Test/TestCase/CreateIntegrationEntityTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/global/variations.xsd">
    <testCase name="CreateIntegrationEntityTest">
        <variation name="CreateIntegrationEntityTestVariation1">
            <data name="integration/data/name">Integration%isolation%</data>
            <data name="integration/data/email">test@example.com</data>
            <data name="integration/data/endpoint">https://endpoint.com</data>
            <data name="integration/data/identity_link_url">https://testlink.com</data>
            <data name="integration/data/resource_access">All</data>
            <data name="integration/data/resources">-</data>
            <data name="constraint">assertIntegrationSuccessSaveMessage, assertIntegrationForm, assertIntegrationInGrid</data>
        </variation>
        <variation name="CreateIntegrationEntityTestVariation2">
            <data name="integration/data/name">Integration%isolation%</data>
            <data name="integration/data/email">-</data>
            <data name="integration/data/endpoint">-</data>
            <data name="integration/data/identity_link_url">-</data>
            <data name="integration/data/resource_access">Custom</data>
            <data name="integration/data/resources">Sales</data>
            <data name="constraint">assertIntegrationSuccessSaveMessage, assertIntegrationForm, assertIntegrationInGrid</data>
        </variation>
        <variation name="CreateIntegrationEntityTestVariation3">
            <data name="integration/data/name">Integration%isolation%</data>
            <data name="integration/data/email">-</data>
            <data name="integration/data/endpoint">-</data>
            <data name="integration/data/identity_link_url">-</data>
            <data name="integration/data/resource_access">All</data>
            <data name="integration/data/resources">-</data>
            <data name="constraint">assertIntegrationSuccessSaveMessage, assertIntegrationForm, assertIntegrationInGrid</data>
        </variation>
    </testCase>
</config>

=== matkowalski/magento2/dev/tests/functional/tests/app/Magento/CatalogSearch/Test/TestCase/SuggestSearchingResultEntityTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/global/variations.xsd">
    <testCase name="SuggestSearchingResultEntityTest">
        <variation name="SuggestSearchingResultEntityTestVariation1">
            <data name="catalogSearch/data/query_text/value">catalogProductSimple::name</data>
            <data name="catalogSearch/data/num_results">-</data>
            <data name="constraint">assertSuggestSearchingResult</data>
        </variation>
        <variation name="SuggestSearchingResultEntityTestVariation2">
            <data name="catalogSearch/data/query_text/value">catalogProductSimple::sku</data>
            <data name="catalogSearch/data/num_results">1</data>
            <data name="constraint">assertSuggestSearchingResult</data>
        </variation>
    </testCase>
</config>

=== matkowalski/magento2/dev/tests/functional/tests/app/Magento/Review/Test/TestCase/UpdateProductReviewEntityOnProductPageTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/global/variations.xsd">
    <testCase name="UpdateProductReviewEntityOnProductPageTest">
        <variation name="UpdateProductReviewEntityOnProductPageTestVariation1">
            <data name="rating">3</data>
            <data name="review/data/status_id">Approved</data>
            <data name="productRating/data/select_stores">Main Website/Main Website Store/Default Store View</data>
            <data name="review/data/nickname">name%isolation%</data>
            <data name="review/data/title">title%isolation%</data>
            <data name="review/data/detail">details%isolation%</data>
            <data name="constraint">assertProductReviewBackendSuccessSaveMessage, assertProductReviewInGrid, assertProductReviewOnProductPage, assertProductRatingInProductPage</data>
        </variation>
    </testCase>
</config>

=== matkowalski/magento2/dev/tests/functional/tests/app/Magento/Checkout/Test/TestCase/UpdateShoppingCartTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/global/variations.xsd">
    <testCase name="UpdateShoppingCartTest">
        <variation name="UpdateShoppingCartTestVariation1">
            <data name="product/dataSet">default</data>
            <data name="product/data/price/value">100</data>
            <data name="product/data/checkout_data/qty">3</data>
            <data name="product/data/checkout_data/cartItem/price">100</data>
            <data name="product/data/checkout_data/cartItem/subtotal">300</data>
            <data name="constraint">assertPriceInShoppingCart, assertProductQtyInShoppingCart, assertProductQtyInMiniShoppingCart, assertSubtotalInShoppingCart</data>
        </variation>
        <variation name="UpdateShoppingCartTestVariation2">
            <data name="product/dataSet">with_two_custom_option</data>
            <data name="product/data/price/value">50</data>
            <data name="product/data/checkout_data/qty">11</data>
            <data name="product/data/checkout_data/cartItem/price">65</data>
            <data name="product/data/checkout_data/cartItem/subtotal">715</data>
            <data name="constraint">assertPriceInShoppingCart, assertProductQtyInShoppingCart, assertProductQtyInMiniShoppingCart, assertSubtotalInShoppingCart</data>
        </variation>
    </testCase>
</config>

=== matkowalski/magento2/dev/tests/functional/tests/app/Magento/CatalogRule/Test/TestCase/ApplySeveralCatalogPriceRuleEntityTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/global/variations.xsd">
    <testCase name="ApplySeveralCatalogPriceRuleEntityTest">
        <variation name="ApplySeveralCatalogPriceRuleEntityTestVariation1">
            <data name="catalogRulesOriginal/priority_0">catalog_price_rule_priority_0</data>
            <data name="catalogRulesOriginal/priority_1">-</data>
            <data name="catalogRulesOriginal/priority_2">catalog_price_rule_priority_2</data>
            <data name="price/sub_total">100</data>
            <data name="price/grand_total">40</data>
            <data name="price/discount_amount">60</data>
            <data name="price/special">40</data>
            <data name="price/regular">100</data>
            <data name="constraint">assertCatalogPriceRuleAppliedCatalogPage, assertCatalogPriceRuleAppliedProductPage, assertCatalogPriceRuleAppliedShoppingCart</data>
        </variation>
        <variation name="ApplySeveralCatalogPriceRuleEntityTestVariation2">
            <data name="catalogRulesOriginal/priority_0">catalog_price_rule_priority_0</data>
            <data name="catalogRulesOriginal/priority_1">catalog_price_rule_priority_1_stop_further_rules</data>
            <data name="catalogRulesOriginal/priority_2">catalog_price_rule_priority_2</data>
            <data name="price/sub_total">100</data>
            <data name="price/grand_total">45</data>
            <data name="price/discount_amount">55</data>
            <data name="price/special">45</data>
            <data name="price/regular">100</data>
            <data name="constraint">assertCatalogPriceRuleAppliedCatalogPage, assertCatalogPriceRuleAppliedProductPage, assertCatalogPriceRuleAppliedShoppingCart</data>
        </variation>
    </testCase>
</config>

=== matkowalski/magento2/dev/tests/functional/tests/app/Magento/User/Test/TestCase/DeleteAdminUserEntityTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/global/variations.xsd">
    <testCase name="DeleteAdminUserEntityTest">
        <variation name="DeleteAdminUserEntityTestVariation1">
            <data name="isDefaultUser">0</data>
            <data name="constraint">assertImpossibleDeleteYourOwnAccount, assertUserInGrid</data>
        </variation>
        <variation name="DeleteAdminUserEntityTestVariation2">
            <data name="isDefaultUser">1</data>
            <data name="constraint">assertUserSuccessDeleteMessage, assertUserNotInGrid</data>
        </variation>
    </testCase>
</config>
